// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDik9_x54CA_-QGujxyyy9FdoY6gYRB3Fo',
    appId: '1:295826911945:web:6cc5a324738784ad049318',
    messagingSenderId: '295826911945',
    projectId: 'onlinelearning-39624',
    authDomain: 'onlinelearning-39624.firebaseapp.com',
    storageBucket: 'onlinelearning-39624.firebasestorage.app',
    measurementId: 'G-TBX2V1PLXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMf0us6xzeDz9ObaW52Q-NqDF9l0pqZNc',
    appId: '1:295826911945:android:44452c82a401501b049318',
    messagingSenderId: '295826911945',
    projectId: 'onlinelearning-39624',
    storageBucket: 'onlinelearning-39624.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNupGWEBj6R70TKf8UhQW7rjlVe7TemMo',
    appId: '1:295826911945:ios:8f1d92c8c95a26b0049318',
    messagingSenderId: '295826911945',
    projectId: 'onlinelearning-39624',
    storageBucket: 'onlinelearning-39624.firebasestorage.app',
    iosBundleId: 'com.example.onlinelearningplatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNupGWEBj6R70TKf8UhQW7rjlVe7TemMo',
    appId: '1:295826911945:ios:8f1d92c8c95a26b0049318',
    messagingSenderId: '295826911945',
    projectId: 'onlinelearning-39624',
    storageBucket: 'onlinelearning-39624.firebasestorage.app',
    iosBundleId: 'com.example.onlinelearningplatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDik9_x54CA_-QGujxyyy9FdoY6gYRB3Fo',
    appId: '1:295826911945:web:2e53cbdca89ebf9e049318',
    messagingSenderId: '295826911945',
    projectId: 'onlinelearning-39624',
    authDomain: 'onlinelearning-39624.firebaseapp.com',
    storageBucket: 'onlinelearning-39624.firebasestorage.app',
    measurementId: 'G-0ZLNNENMW2',
  );

}